In [49]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [50]:
df = pd.read_csv('/Users/cateslaven/Desktop/A- Predictive Analysis/crime project/crimedata2 (1).csv', encoding = 'latin-1')
df.head()

crimes_df = df[['rapes', 'rapesPerPop', 'assaults', 'assaultPerPop', 'ViolentCrimesPerPop']]
print(crimes_df.head())
print(crimes_df.dtypes)  # Check the data types

  rapes rapesPerPop assaults assaultPerPop ViolentCrimesPerPop
0     0           0        4         32.81               41.02
1     1        4.25       24        102.05              127.56
2     6        16.6       14         38.74              218.59
3    10       57.86       33        190.93              306.64
4     ?           ?       14        112.14                   ?
rapes                  object
rapesPerPop            object
assaults               object
assaultPerPop          object
ViolentCrimesPerPop    object
dtype: object

In [51]:
#these variables contain data about variables that directly impact/represent familial relations
family_df = df[['PopDens','PersPerFam','PctFam2Par','MalePctDivorce','MalePctNevMarr','FemalePctDiv','TotalPctDiv','PctWorkMom','PctKids2Par','PctYoungKids2Par','PctTeen2Par','PctWorkMomYoungKids','NumImmig','PctImmigRecent','PersPerOccupHous']]
family_df

,PopDens,PersPerFam,PctFam2Par,MalePctDivorce,MalePctNevMarr,FemalePctDiv,TotalPctDiv,PctWorkMom,PctKids2Par,PctYoungKids2Par,PctTeen2Par,PctWorkMomYoungKids,NumImmig,PctImmigRecent,PersPerOccupHous
0,1845.9,3.22,91.43,3.67,26.38,5.22,4.47,58.88,90.17,95.78,95.81,44.56,1277,8.69,2.99
1,2186.7,3.11,86.91,4.23,27.99,6.45,5.42,62.43,85.33,96.82,86.46,51.14,1920,5.21,2.70
2,2780.9,2.95,78.54,10.10,25.78,14.76,12.55,74.19,78.85,92.37,75.72,66.08,1468,16.42,2.42
3,3217.7,2.98,64.02,10.98,28.15,14.47,12.91,70.27,62.36,65.38,67.43,59.59,339,13.86,2.37
4,974.2,2.98,58.59,7.51,50.66,11.64,9.73,68.94,55.20,66.51,79.17,61.22,196,46.94,2.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2210,3365.4,3.56,67.04,10.22,31.91,16.28,13.34,55.38,64.81,76.19,72.78,47.24,10623,22.97,3.03
2211,1682.8,3.12,68.57,10.86,29.51,16.12,13.77,66.67,63.66,80.29,73.68,64.20,275,2.91,2.49
2212,1195.2,2.99,76.77,9.89,20.56,12.38,11.23,62.62,74.20,76.92,82.42,55.73,2414,6.63,2.44
2213,2142.2,3.46,67.76,10.35,29.18,14.36,12.48,60.14,63.45,87.82,74.12,50.57,309,4.85,2.84
2214,1331.0,3.20,62.64,15.77,29.72,18.84,17.31,57.32,60.23,72.43,66.15,50.44,4765,31.54,2.58

In [52]:
#next step is to identify possible correlations between violent crimes
crimes_df = df[['rapes','rapesPerPop','assaults','assaultPerPop','ViolentCrimesPerPop']]
crimes_df

     rapes rapesPerPop assaults assaultPerPop ViolentCrimesPerPop
0        0           0        4         32.81               41.02
1        1        4.25       24        102.05              127.56
2        6        16.6       14         38.74              218.59
3       10       57.86       33        190.93              306.64
4        ?           ?       14        112.14                   ?
...    ...         ...      ...           ...                 ...
2210    30       49.46      170        280.29              545.75
2211     4       33.09       10         82.73               124.1
2212     5       13.61       96        261.29              353.83
2213     2       15.71       79        620.48              691.17
2214    19        62.8      152        502.41              918.89

[2215 rows x 5 columns]

In [53]:
null_counts = crimes_df.apply(lambda x : x.isna().sum())
print(null_counts)

rapes                  0
rapesPerPop            0
assaults               0
assaultPerPop          0
ViolentCrimesPerPop    0
dtype: int64

In [58]:
print(crimes_df['rapes'].unique())

crimes_df.replace("?", np.nan, inplace=True)

crimes_df.dropna(inplace=True)

crimes_df = crimes_df.apply(pd.to_numeric, errors='coerce')

print(crimes_df['rapes'].unique())

[   0    1    6   10   77    4   34   35  141   29   21   36   59   30
    2  146 2818    9   42   20   24    7    3   14   43   37    5    8
   16  357  785   11   45   15   33   23  102   13  314   31   19   22
  479  130   41  137   28 1773   17   12  112   40   18   53  247 1000
   82   39  200  515   26  129  265  204   58   38   27   67  295   55
   47   57   89   52  167   25  507   75  104   60  361   49  393  103
   66  480   99   87   78   79   32  177   68   62  339   81  215   98
  173  269  281  159   65   94   90  271  391   50  356  154  298  122
  658  668  725   51   54   84   44  111  212   46  216  174  135   48
   61  109  449  435  136  209  353  257   88   64  114   71   73  297
   72  518  396  553  166  191  424  324  492   70  699  100   76   80
   56  226  116  157  259   83  194  131   92  105  517  834  181  444
  106]
[   0    1    6   10   77    4   34   35  141   29   21   36   59   30
    2  146 2818    9   42   20   24    7    3   14   43   37    5    8
   16  357  785   11   45   15   33   23  102   13  314   31   19   22
  479  130   41  137   28 1773   17   12  112   40   18   53  247 1000
   82   39  200  515   26  129  265  204   58   38   27   67  295   55
   47   57   89   52  167   25  507   75  104   60  361   49  393  103
   66  480   99   87   78   79   32  177   68   62  339   81  215   98
  173  269  281  159   65   94   90  271  391   50  356  154  298  122
  658  668  725   51   54   84   44  111  212   46  216  174  135   48
   61  109  449  435  136  209  353  257   88   64  114   71   73  297
   72  518  396  553  166  191  424  324  492   70  699  100   76   80
   56  226  116  157  259   83  194  131   92  105  517  834  181  444
  106]

In [59]:
# Replace "?" with NaN
crimes_df.replace("?", np.nan, inplace=True)

# Convert to numeric and drop NaN values
crimes_df = crimes_df.apply(pd.to_numeric, errors='coerce')
crimes_df.dropna(inplace=True)

# Check for any remaining NaN values
print(crimes_df.isna().sum())

rapes                  0
rapesPerPop            0
assaults               0
assaultPerPop          0
ViolentCrimesPerPop    0
dtype: int64

In [60]:
crimes_df = df[['rapes','rapesPerPop','assaults','assaultPerPop','ViolentCrimesPerPop']]

print(crimes_df.dtypes)

rapes                  object
rapesPerPop            object
assaults               object
assaultPerPop          object
ViolentCrimesPerPop    object
dtype: object

In [62]:
# Identify outliers using IQR method


for column in crimes_df.columns:
    Q1 = crimes_df[column].quantile(0.25)
    Q3 = crimes_df[column].quantile(0.75)
    IQR = Q3 - Q1
    
    # Define bounds for outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    # Identify outliers
    outliers = crimes_df[(crimes_df[column] < lower_bound) | (crimes_df[column] > upper_bound)]
    
    # Print results
    print(f"Column: {column}")
    print(f"Q1: {Q1}")
    print(f"Q3: {Q3}")
    print(f"IQR: {IQR}")
    print(f"Outliers:\n{outliers}\n")

# for col in crimes_df.columns:
#     plt.figure(figsize=(8, 6))
#     sns.boxplot(x=crimes_df[col])
#     plt.title(col)
#     plt.show()

#     # Set up the figure and axes
# plt.figure(figsize=(12, 8))
# sns.boxplot(data=crimes_df)

# # Add titles and labels
# plt.title('Boxplots of Violent Crime Metrics', fontsize=16)
# plt.xlabel('Crime Metrics', fontsize=14)
# plt.ylabel('Values', fontsize=14)

# # Show the plot
# plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
# plt.show()

crimes_df

TypeError: unsupported operand type(s) for -: 'str' and 'str'